LoanPaymentCalculator/Models/LoanViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using LoanPaymentCalculator.Core.Models;

namespace LoanPaymentCalculator.Models
{
    public class LoanViewModel
    {
        [DisplayName("Loan amount: ")]
        public int LoanAmount { get; set; }

        [DisplayName("Loan term in years")]
        public int LoanTermInYears { get; set; }

        public List<Payment> Payments { get; set; }
    }
}

LoanPaymentCalculator/ViewModels/LoanViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using LoanPaymentCalculator.Core.Models;

namespace LoanPaymentCalculator.ViewModels
{
    public class LoanViewModel
    {
        [DisplayName("Loan amount: ")]
        public int LoanAmount { get; set; }

        [DisplayName("Loan term in years: ")]
        public int LoanTermInYears { get; set; }

        public List<Payment> Payments { get; set; }
    }
}

LoanPaymentCalculator/Controllers/LoanController.cs
using Microsoft.AspNetCore.Mvc;
using LoanPaymentCalculator.ViewModels;
using LoanPaymentCalculator.Core.Models;

namespace LoanPaymentCalculator.Controllers
{
    public class LoanController : Controller
    {
        private readonly IPaymentCalculator _paymentCalculator;
        private readonly LoanFactory _loanFactory;

        public LoanController(IPaymentCalculator paymentCalculator, LoanFactory loanFactory)
        {
            _paymentCalculator = paymentCalculator;
            _loanFactory = loanFactory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(LoanViewModel model)
        {
            BaseLoan loan = _loanFactory.CreateHousingLoan(model.LoanAmount, model.LoanTermInYears);
            model.Payments = _paymentCalculator.CalculatePayments(loan);
            return View(model);
        }
    }
}

LoanPaymentCalculator/Views/Loan/Index.cshtml
@model LoanViewModel

<div class="text-center col-md-6 offset-md-3">
    <h1 class="display-5">Loan Payment Calculator</h1>
    <form asp-action="Index" asp-controller="Loan">
        <div class="mb-3">
            <label class="form-label" asp-for="LoanAmount"></label>
            <div class="input-group">
                <input class="form-control" min="1" max="2147483647" asp-for="LoanAmount" />
                <div class="input-group-append">
                    <span class="input-group-text">SEK</span>
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="LoanTermInYears"></label>
            <div class="input-group">
                <input class="form-control" min="1" max="99" asp-for="LoanTermInYears" />
                <div class="input-group-append">
                    <span class="input-group-text">years</span>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Calculate</button>
    </form>
</div>

@if (Model != null)
{
    <div class="col-md-8 offset-md-2">
        <h1 class="text-center">Your monthly payment is @Model.Payments[0].AmountToPay SEK.</h1>

        <table class="table table-striped table-hover">
            <tr>
                <th>Date</th>
                <th>Payment</th>
                <th>Interest</th>
                <th>Principal</th>
                <th>Balance</th>
            </tr>
            @foreach (Payment payment in Model.Payments)
            {
                <tr>
                    <td>@payment.Date</td>
                    <td>@payment.AmountToPay SEK</td>
                    <td>@payment.Interest SEK</td>
                    <td>@payment.Principal SEK</td>
                    <td>@payment.AmountLeft SEK</td>
                </tr>
            }
        </table>
    </div>
}

LoanPaymentCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoanPaymentCalculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Loan" asp-action="Index">LoanPaymentCalculator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>